# This file formated for https://marketplace.visualstudio.com/items?itemName=humao.rest-client

###

GET http://localhost:3000/notes HTTP/1.1

###

POST http://localhost:3000/notes HTTP/1.1
content-type: application/json

{
    "id": "2",
    "title": "hello",
    "desc": "world",
    "order": 0,
    "color": "#FFFFFF",
    "colorId": 0
}

###

GET http://localhost:3000/notes/1 HTTP/1.1

###

PUT http://localhost:3000/notes/1 HTTP/1.1
content-type: application/json

{
"id": "1",
"title": "cruel",
"desc": "world",
"order": 0,
"color": "#FFFFFF",
"colorId": 0
}

###

DELETE http://localhost:3000/notes/1 HTTP/1.1

###